#!/bin/bash

set INPFILE=$argv[1]

#  $? hold exit status of last executed commmand
#   $1 is first command line argument

echo $0
echo $INPFILE

STRING="meow"
TW=wow

echo $STRING
echo $TW

touch meow.script

echo '#~/bin/bash' dafdsa

#if statement
if [ $STRING!=$TW ]; then
	echo true
else 
	echo false
fi


#for loop
for i in `seq 1 10`;
do
	echo $i;
done

function e {
	echo $1
}

e Hello!
echo hello!!!!!!
echo $INPFILE