#!/bin/bash

INPFILE=$1

target_file=/var/www/html/EFPDB/database/qsub_inp/$INPFILE.script

#overwrite any previous by the same name
echo '#!/bin/csh' > $target_file
chmod 755 $target_file

echo '#PBS -q batch' >> $target_file
echo '#PBS -l nodes=1:ppn=1' >> $target_file
echo '#PBS -l walltime=300:00:00' >> $target_file
echo "#PBS -r n" >> $target_file
echo "#PBS -j oe" >> $target_file
echo "#PBS -o $INPFILE.stdout" >> $target_file
echo "#PBS -N $INPFILE" >> $target_file

echo "chdir /var/www/html/EFPDB/database/gamess_inp_files" >> $target_file

#Thr final command to execute GAMESS
echo "/software/gamess/rungms $INPFILE 00 1 >& ../log_files/$INPFILE.log" >> $target_file

qsub $target_file
